### ISSUE TITLE
deprecate all redundant functions

### ISSUE THREAD

**Issue by schveiguy** [schveiguy/draylib#13]
raylib has a *ton* of functions that are redundant given that they are included in Phobos. I'm currently porting a ton of functions that just parse filenames and get extensions/filenames/etc. These can all be done via `std.path`.

There are undoubtedly a lot of these in raylib. He tried to make it a one-stop-shop for library code. But we have a better one!

So we need to deprecate all these, and point people at the correct phobos functions.

This will probably trim a good chunk of rcore out, making it less for us to maintain. A lot of these are *really* unsafe too.

**Comment by jordan4ibanez** [comment]
This is also a great idea!!
