### ISSUE TITLE
Investigate using glfw-d

### ISSUE THREAD

**Issue by schveiguy** [schveiguy/draylib#4]
Dennis Korpel has ported glfw directly to D! When we are done with the raylib port, and ready to switch to using more D features, we can probably look at using that lib instead of bindbc-glfw so we don't have to do funky library stuff. Plus, we otherwise need to build or include glfw binaries.

**Comment by schveiguy** [comment]
We might do this sooner rather than later. Discovering the tool Dennis created and how it is possible to port everything, we can probably just start depending on this directly instead of using the included glfw.

**Comment by jordan4ibanez** [comment]
This is absolutely a great decision!

**Comment by RealDoigt** [comment]
Considering our talk last night about the internal dependencies, does it really matter if we actually depend on D instead of the C implementation? The other internal dependencies are not planned to be ported to C; it would be inconsistent to depend on glfw-d.

**Comment by schveiguy** [comment]
Correct, we are going to just use importC for glfw.
